target 'Megazord_Poke_iOS' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'Megazord_Poke_KMM', :path => '../Megazord_Poke_KMM/module'
  
  pod 'Flutter', :podspec => '../Megazord_Poke_Flutter/build/ios/framework/Debug/Flutter.podspec'
  pod 'Megazord_Poke_Flutter', :path => '../Megazord_Poke_Flutter'
end
